# Azure AI Foundry Workflow Configuration
# Orchestrates the Weather Clothing Advisor agent workflow

name: weather-clothing-advisor-workflow
description: POC workflow demonstrating weather lookup and clothing recommendations
version: 1.0.0

# Workflow configuration
workflow:
  # Entry point agent
  agent: WeatherClothingAdvisor
  agent_config: ./agent.yaml

  # Workflow type
  type: conversational

  # Input/output schema
  input:
    type: object
    properties:
      message:
        type: string
        description: User's natural language query (e.g., 'What should I wear in 10001?')
      session_id:
        type: string
        description: Optional session ID for conversation continuity
        required: false

  output:
    type: object
    properties:
      response:
        type: string
        description: Agent's clothing recommendation response
      session_id:
        type: string
        description: Session ID for tracking conversation
      metadata:
        type: object
        description: Response metadata (response time, tool calls, etc.)

# Workflow steps
steps:
  - id: parse_user_input
    description: Parse user message to identify zip code and intent
    agent: WeatherClothingAdvisor

  - id: get_weather_data
    description: Call weather function tool with extracted zip code
    depends_on: parse_user_input
    tool: get_weather
    conditional:
      # Only call if zip code was identified
      condition: has_zip_code

  - id: generate_recommendations
    description: Generate clothing recommendations based on weather
    depends_on: get_weather_data
    agent: WeatherClothingAdvisor

  - id: format_response
    description: Format recommendations in user-friendly manner
    depends_on: generate_recommendations
    agent: WeatherClothingAdvisor

# Performance constraints (SC-001)
performance:
  max_duration_seconds: 5
  warn_threshold_seconds: 4

# Error handling
error_handling:
  strategy: graceful_degradation
  fallback_messages:
    invalid_zip: "I couldn't find weather data for that zip code. Please provide a valid 5-digit US zip code."
    api_timeout: "The weather service is taking too long to respond. Please try again in a moment."
    network_error: "I'm having trouble connecting to the weather service. Please check your connection and try again."

# Telemetry configuration
telemetry:
  enabled: true
  track_events:
    - workflow_start
    - workflow_complete
    - tool_call
    - agent_response
    - error
  custom_dimensions:
    workflow_type: conversational
    deployment_type: foundry-agent
    poc_version: 1.0.0

# Integration with Azure resources
azure:
  # AI Foundry project
  project_endpoint: ${AZURE_AI_PROJECT_ENDPOINT}

  # Application Insights
  application_insights:
    connection_string: ${APPLICATIONINSIGHTS_CONNECTION_STRING}

  # Weather Function
  functions:
    - name: get_weather
      endpoint: ${WEATHER_FUNCTION_URL}
      authentication: function_key

# Deployment configuration
deployment:
  region: swedencentral
  environment: ${ENVIRONMENT:production}
  scaling:
    min_instances: 1
    max_instances: 3
    scale_trigger: conversation_load

# Validation rules (Success Criteria)
validation:
  # SC-001: Response time
  response_time:
    max_seconds: 5
    log_violations: true

  # SC-002: Recommendation count
  recommendation_count:
    min: 3
    max: 5
    validate: true

  # SC-003: Weather data accuracy
  weather_data:
    require_valid_source: true
    max_age_minutes: 5

  # SC-004: Language quality
  language:
    require_explanations: true
    check_readability: true

  # SC-005: Re-lookup support
  multi_lookup:
    enable_session_tracking: true
    preserve_conversation_context: true

# Development and testing
development:
  enable_debug_logs: ${DEBUG:false}
  mock_mode: ${MOCK_MODE:false}
  test_mode: ${TEST_MODE:false}
